name: publish

on: [push]

jobs:
  publish-mini-ota-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the mini-ota Docker image
      run: |
        docker build . --tag ghcr.io/lineageos4microg/mini-ota:latest
        docker run ghcr.io/lineageos4microg/mini-ota:latest
        docker push ghcr.io/lineageos4microg/mini-ota:latest
